server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://knitting-auth:8082/
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: LoggingFilter
        - id: server
          uri: http://knitting-server:8081/
          predicates:
            - Path=/api/**
          filters:
            - name: LoggingFilter
