spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    region: ap-northeast-2
    stack:
      auto: false
  s3:
    bucket: knitting-storage
    access-key:
    secret-key:
